#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &




# set some bsp specific
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap 12
bspc config border_width 2

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# AutoStart apps
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar example &